### ISSUE TITLE
Spaces in folders name

### ISSUE THREAD

**Issue by badpush** [valsou/bellerophon#4]
I have an error like this :  Invalid group name 'Amstrad CPC'. Try quoting it. (line 14 column 1 char 454)
The space in folder name generate issue

**Comment by valsou** [comment]
Hi,

TOML (language used for the configuration file) does not allow spaces in keys; e.g `[systems.NAME]`. Unfortunately the only solution will be to write `AmstradCPC` or `Amstrad_CPC` for your folder.

I'll we see how to do better and accept a larger range of naming conventions.

Thanks for your message.

**Comment by valsou** [comment]
Nevermind. It works if you quote the last part.

`[systems."Amstrad CPC"]`

You can close the issue if it's OK.

Thanks. ;)
